-- Supabase SQL Editor 中执行，用于补齐 MVP 所需的数据表和存储配置。

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'checkins_user_id_date_unique'
  ) then
    alter table checkins
    add constraint checkins_user_id_date_unique unique (user_id, date);
  end if;
end $$;

alter table checkins enable row level security;

drop policy if exists "Allow anon read checkins" on checkins;
create policy "Allow anon read checkins"
on checkins
for select
to anon
using (true);

drop policy if exists "Allow anon insert checkins" on checkins;
create policy "Allow anon insert checkins"
on checkins
for insert
to anon
with check (true);

create table if not exists weekly_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  note text default '',
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table weekly_progress enable row level security;

drop policy if exists "Allow anon read weekly progress" on weekly_progress;
create policy "Allow anon read weekly progress"
on weekly_progress
for select
to anon
using (true);

drop policy if exists "Allow anon insert weekly progress" on weekly_progress;
create policy "Allow anon insert weekly progress"
on weekly_progress
for insert
to anon
with check (true);

create table if not exists study_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  deadline timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table study_tasks enable row level security;

drop policy if exists "Allow anon read active study tasks" on study_tasks;
create policy "Allow anon read active study tasks"
on study_tasks
for select
to anon
using (is_active = true);

drop policy if exists "Allow anon insert study tasks" on study_tasks;
create policy "Allow anon insert study tasks"
on study_tasks
for insert
to anon
with check (true);

create table if not exists meeting_replays (
  id bigint generated by default as identity primary key,
  title text not null,
  replay_date date not null,
  duration text,
  url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table meeting_replays enable row level security;

drop policy if exists "Allow anon read active meeting replays" on meeting_replays;
create policy "Allow anon read active meeting replays"
on meeting_replays
for select
to anon
using (is_active = true);

insert into storage.buckets (id, name, public)
values ('weekly-progress', 'weekly-progress', true)
on conflict (id) do update set public = true;

drop policy if exists "Allow anon read weekly progress images" on storage.objects;
create policy "Allow anon read weekly progress images"
on storage.objects
for select
to anon
using (bucket_id = 'weekly-progress');

drop policy if exists "Allow anon upload weekly progress images" on storage.objects;
create policy "Allow anon upload weekly progress images"
on storage.objects
for insert
to anon
with check (bucket_id = 'weekly-progress');

insert into study_tasks (title, content, deadline, is_active)
select
  '第 1 章核心概念背诵',
  '请完成本章核心概念背诵，并用自己的话整理概念之间的关系。',
  '2026-06-23 23:59:00+08',
  true
where not exists (
  select 1 from study_tasks where title = '第 1 章核心概念背诵'
);

insert into study_tasks (title, content, deadline, is_active)
select
  '本周专业课框架图',
  '请把本周背诵内容整理成一页纸思维导图或分级大纲，并在周进度页面上传。',
  '2026-06-27 23:59:00+08',
  true
where not exists (
  select 1 from study_tasks where title = '本周专业课框架图'
);

insert into meeting_replays (title, replay_date, duration, url, is_active)
select '专业课导论与复习规划', '2026-06-18', '1小时32分', 'https://meeting.tencent.com/', true
where not exists (
  select 1 from meeting_replays where title = '专业课导论与复习规划'
);

insert into meeting_replays (title, replay_date, duration, url, is_active)
select '专业课核心章节串讲', '2026-06-15', '2小时05分', 'https://meeting.tencent.com/', true
where not exists (
  select 1 from meeting_replays where title = '专业课核心章节串讲'
);
